name: Spade
version: 0.0.1-SNAPSHOT
main: net.nexisonline.spade.SpadePlugin
commands:
  setworldgen:
    description: Set the Chunk Provider
    usage: What
  tpw:
    description: TP to some world
    usage: /tpw <worldname>
  regen:
    description: Regenerate the chunk you're standing in
    usage: /regen chunk